### ISSUE TITLE
reversed orientation - mesh generation

### ISSUE THREAD

**Issue by brianjiang1572** [SCOREC/Fusion_Public#13]
Mesh generation with double null produces incorrect mesh when inner separatrix is above the magnetic axis (which is the reversed of the usual orientation). The flux surfaces associated with unaligned points appear to be off by -1 or -2, which throws an "Error in setup of field-line following coordinate" in line 1336 within search.F90 of XGC Devel. 

An example case is contained in /p/epsi/rhager/double_null_problems.zip. Within the zip file, there is a folder reverse_z containing an example g184828.01820, with an eqdsk file and an input file.

**Comment by usmanriaz07** [comment]
@brianjiang1572 I will look at this issue in 2-3 days and will try to provide you an update on it before the end of the week.

**Comment by rhager** [comment]
Thanks, @usmanriaz07!

**Comment by usmanriaz07** [comment]
@brianjiang1572 I have looked into it, and apparently, the flux curves associated with the unaligned vertices are reported correctly. If you look at the attached picture (I am not sure if you will be able to zoom in or not), the unaligned vertices are shown in blue with the vertex number, inner separatrix in red (numbered 52), and outer separatrix in green (numbered 53). All other flux curves are in red, with the flux curve number on every vertex.  You can see that the data is consistent with the data provided in the flx.aif file (I attached an image of the data too). 
![Capture](https://github.com/SCOREC/Fusion_Public/assets/43378634/6974c348-ec61-4236-8d17-a425035d6915)
![nodes](https://github.com/SCOREC/Fusion_Public/assets/43378634/df15c5af-d1f8-4ca6-8692-24ef88e414ff)


Do you think the error might be because of some assumptions in XGC for such cases? The mesh data looks consistent for this particular case.

**Comment by usmanriaz07** [comment]
Zoomed-in plots of regions with unaligned vertices.

![lowerLeft](https://github.com/SCOREC/Fusion_Public/assets/43378634/86baf799-0c3b-444d-a203-bba4d2d2a53b)
![lowerRight](https://github.com/SCOREC/Fusion_Public/assets/43378634/ba961831-bd30-4d3d-9b3b-7381a7adf181)
![topLeft](https://github.com/SCOREC/Fusion_Public/assets/43378634/c44bad80-2b5f-427c-914f-99c2cd1848d7)
![topRight](https://github.com/SCOREC/Fusion_Public/assets/43378634/3905da32-3787-40cb-a828-c1afa6727448)

**Comment by brianjiang1572** [comment]
Thanks Usman. Will check to see if there is an XGC assumption causing the issue.

**Comment by brianjiang1572** [comment]
I made a mistake with the eqd file; no issues meshing/psi computation in XGC.
