### ISSUE TITLE
double null, single flux surface

### ISSUE THREAD

**Issue by brianjiang1572** [SCOREC/Fusion_Public#14]
Mesh generation fails on double null where two separatrices have `psi` values close enough to lie on the same flux surface. Adding  `useOuterSeparatrix 1` breaks mesh generation. 

Two example cases are in  /p/epsi/rhager/double_null_problems.zip. Within the zip file, there is a folder single_psi_double_null containing two double null cases where both separatrices have close `psi`.

**Comment by usmanriaz07** [comment]
@brianjiang1572  do you get a valid mesh when you set useOuterSeparatrix 0?

**Comment by rhager** [comment]
Yes, I think so. But @brianjiang1572 should confirm. In this case, it may be worthwhile to print an error message (e.g. saying that `useOuterSeparatrix 1` does not work if `psi_x1-psi_x2<epsilon`) and exit the program in a controlled way instead of letting it run into a segfault.

**Comment by brianjiang1572** [comment]
Yes, a valid mesh is obtained with`useOuterSeparatrix 0` (without, of course, the second separatrix)

**Comment by usmanriaz07** [comment]
I have updated the TOMMS that will include an error message with a safe exit when the psi values of two separatrices are within a certain limit ( (normalized(psiXpt1) - normalized(psiXpt2) < 1e-3). I have installed the updated version on the Centos:
/p/epsi/rpi/install/TOMMS/2023_07_31/bin/tomms_meshgen

I am closing this issue since the basic issue has been addressed. We can reopen the issue in the future if we face any other problems in similar cases.
