### ISSUE TITLE
Wrong data in flx.aif file for an NSTX case

### ISSUE THREAD

**Issue by rhager** [SCOREC/Fusion_Public#15]
@usmanriaz07, I found why I was having problems with the NSTX cases I am working on for the meshing paper. Apparently, there is some wrong information in the `flx.aif` files. I copied the setup for the two cases (identical except that one is with `transitionFacesOn=1`, and one with `0`) to `/p/epsi/rhager`, files `nstx_132588_xgca_v2.tar` and `nstx_132588_xgca_v2a.tar`.

- In case `v2a` (w/o transition faces), the index of the 2nd separatrix is off by `1`. It should be `65` instead of `64`. Otherwise, the file seems to be ok.
- In case `v2`, the index of the 2nd separatrix is off by `2` (should be `66` instead of `64`), and the number of surfaces on the 2nd separatrix is too small by `13` (you can see the missing vertices at the top right in the plots below). This causes a reading error in XGC.

I manually corrected the flx.aif files and will continue to run the simulations.

Here's a plot of the mesh of `v2`. The light yellow/orange line is the surface that's marked as 2nd separatrix. You can see the missing 13 vertices on the upper right separatrix leg.

<img width="597" alt="Screen Shot 2023-08-19 at 7 21 53 AM" src="https://github.com/SCOREC/Fusion_Public/assets/7051856/d48ab1f4-48f6-4385-8d4e-33041b0789a8">

And here is one of `v2a`:
<img width="676" alt="Screen Shot 2023-08-19 at 7 18 04 AM" src="https://github.com/SCOREC/Fusion_Public/assets/7051856/f772631b-543a-4015-9fa4-f98322adfc34">

**Comment by rhager** [comment]
@usmanriaz07, there seems to be another problem with the NSTX mesh with the transition faces. There is at least one invalid triangle. I had issues with XGC's volume calculation. So I manually calculated the triangle surface area and looked at the one with the smaller area. The do appear to be on the same flux-surface.

<img width="1259" alt="Screen Shot 2023-08-21 at 12 30 23 PM" src="https://github.com/SCOREC/Fusion_Public/assets/7051856/98274fcd-2daf-4f38-832e-8c588666d2a9">
<img width="1270" alt="Screen Shot 2023-08-21 at 12 29 25 PM" src="https://github.com/SCOREC/Fusion_Public/assets/7051856/445e47b7-d93e-4537-8ac9-5be3f6005f79">

**Comment by usmanriaz07** [comment]
@rhager  I have fixed the issue with no transition layer case, where index should be 65 instead of 64. In the case with the transition layers, why do you expect the second separatrix to be indexed 66 instead of 65? Since both cases are identical with same number of flux curves between the two separatrices, so shouldn't the second separatrix indexed 65 irrespective of transition layers added or not?

**Comment by rhager** [comment]
If I remember correctly, I just searched for the vertex index of the second
X-point in the surface member list in the flx.aif file.

**Comment by usmanriaz07** [comment]
@rhager I went through both the cases (with and without transition layers) again and they exactly have the same number of flux curves (except for private region). The index for first separatrix is 56, and then there are 7 flux curves between two separatices, with the last one divided into two because of the flux-wall intersections (indexed 63 and 64) and the other six curves are numbered from 57-62. And then the second separatrix is indexed 65. I don't see any reason for the second separatrix to be indexed 66 just by the introduction of the transition layers. Is it possible for you to just double check this information to make sure we are using the same test cases?

**Comment by rhager** [comment]
I'll double-check. Did you compare the number of vertices on the separatrix
surface? There was a difference in the flx.aif files I got. Did you install
the new revision of TOMMS at PPPL? If not, could you send me the meshes you
generated with the fixed TOMMS, please?
